// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNhRhLRlLIRgWTWyU4iFMrcLE63cRo3M',
    appId: '1:772058458212:web:9d3b19a4eff7552037d771',
    messagingSenderId: '772058458212',
    projectId: 'mini-ecommerce-app-8c338',
    authDomain: 'mini-ecommerce-app-8c338.firebaseapp.com',
    storageBucket: 'mini-ecommerce-app-8c338.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU0EVtBv6-J5q3c514RD_l7S53msts-Rs',
    appId: '1:772058458212:android:f24d8a51d7a47ffa37d771',
    messagingSenderId: '772058458212',
    projectId: 'mini-ecommerce-app-8c338',
    storageBucket: 'mini-ecommerce-app-8c338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7n0H1TIHD3ygnbTmYHhzJ9mVFYXXR1zI',
    appId: '1:772058458212:ios:c81ff6b92347297037d771',
    messagingSenderId: '772058458212',
    projectId: 'mini-ecommerce-app-8c338',
    storageBucket: 'mini-ecommerce-app-8c338.firebasestorage.app',
    iosBundleId: 'com.example.miniEcommerce',
  );
}
